# Generated by Django 4.0.6 on 2022-08-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='slug',
        ),
    ]
